### ISSUE TITLE
`@progress` in the terminal

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/Juno.jl#84] opened 2017-11-30 07:49 UTC
I think it would be useful to have `@progress` print out to the terminal a la `curl -#`, or keras' training progress bar, if not running in Juno.  This would be nice to have for e.g. Flux.  What do you think?

**Comment by ChrisRackauckas** [comment] 2017-11-30 13:56
Duplicate of #29

**Closed** 2017-11-30 14:59 UTC
