### ISSUE TITLE
[BUG] Failed to activate the julia-client package: TypeError: Cannot set property 'scrollback' of undefined

### ISSUE THREAD

**Issue by AndiMD** [JunoLab/Juno.jl#306] opened 2019-05-29 06:05 UTC
Hi,

Atom offered me two updates, which I installed (I think it was julia-cient and ink?). After restarting Atom, I got the error below. This makes Julia unusable with Atom.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04.2
**Thrown From**: [julia-client](https://github.com/JunoLab/atom-julia-client) package 0.8.6

### Stack Trace

Failed to activate the julia-client package

```
At Cannot set property 'scrollback' of undefined

TypeError: Cannot set property 'scrollback' of undefined
    at /packages/julia-client/lib/runtime/console2.js:191:37
    at /packages/julia-client/lib/runtime/console2.js:199:7
    at Array.forEach (<anonymous>)
    at forEachPane (/packages/julia-client/lib/runtime/console2.js:197:33)
    at updateTerminalSettings (/packages/julia-client/lib/runtime/console2.js:181:3)
    at Config.observeKeyPath (/usr/share/atom/resources/app/static/<embedded>:11:335098)
    at Config.observe (/usr/share/atom/resources/app/static/<embedded>:11:329580)
    at Object.activate (/packages/julia-client/lib/runtime/console2.js:44:24)
    at Object.consumeInk (/packages/julia-client/lib/runtime.coffee:27:15)
    at Object.consumeInk (/packages/julia-client/lib/julia-client.coffee:43:7)
    at Provider.t.exports.Provider.provide (/usr/share/atom/resources/app/static/<embedded>:14:1046092)
    at ServiceHub.t.exports.ServiceHub.consume (/usr/share/atom/resources/app/static/<embedded>:11:3381070)
    at Package.activateServices (/usr/share/atom/resources/app/static/<embedded>:11:3389202)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3386036)
    at measure (/usr/share/atom/resources/app/static/<embedded>:11:3385360)
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3382991)
    at activationPromise.activationPromise.Promise (/usr/share/atom/resources/app/static/<embedded>:11:3385220)
    at new Promise (<anonymous>)
    at Package.activate (/usr/share/atom/resources/app/static/<embedded>:11:3385163)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382600)
    at config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:382216)
    at Config.transactAsync (/usr/share/atom/resources/app/static/<embedded>:11:332386)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/static/<embedded>:11:382166)
    at PackageManager.activate (/usr/share/atom/resources/app/static/<embedded>:11:381784)
    at t.loadState.then (/usr/share/atom/resources/app/static/<embedded>:1:707960)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
indent-detective 0.3.2 
ink 0.10.8 
julia-client 0.8.6 
language-julia 0.18.1 
latex-completions 0.3.6 
tool-bar 1.1.11 
uber-juno 0.2.0 
```

**Comment by pfitzseb** [comment] 2019-05-29 07:32
Can you try the installation instructions described [here](https://discourse.julialang.org/t/ann-juno-0-8-7/24682)? Namely,
```
apm uninstall ink
apm uninstall julia-client
apm install ink
apm install julia-client
```
in a terminal.

**Comment by AndiMD** [comment] 2019-05-29 11:33
Thanks for the quick help. The reinstallation did not help, but reverting to an older version did:
```
apm uninstall ink
apm uninstall julia-client
apm install ink
apm install julia-client@0.8.3
```

**Comment by pfitzseb** [comment] 2019-05-29 11:48
What OS and Atom version are you on? I can't reproduce the problem on Windows or Linux.

**Comment by pfitzseb** [comment] 2019-05-29 11:51
Nevermind, I think I know what's going on. Will have a fix momentarily.

**Comment by pfitzseb** [comment] 2019-05-29 11:58
Can you try again with julia-client 0.8.7 and report back? Thanks!

**Comment by pfitzseb** [comment] 2019-05-29 18:15
Ok, I got a report that 0.8.8 indeed fixes this. Closing this.

**Closed** 2019-05-29 18:15 UTC
Labels: bug
