### ISSUE TITLE
[BUG] (minor) syntax highlighting issue for long condition

### ISSUE THREAD

**Issue by tlienart** [JunoLab/Juno.jl#354] opened 2019-09-09 11:27 UTC
Atom.jl 0.10.1 
julia client 0.10.1
language-julia 0.19
ink 0.11

Here's a rather ugly line (don't judge), the end is not highlighted properly (last few characters all highlighted as chars, see the last two closing parentheses on the screenshot below). This only happens when the line is fairly long so feel free to close as insignificant issue.

```julia
if scl[1] ∈ ('*', '-', '+') || (length(scl) ≥ 2 && scl[1] ∈ ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') && scl[2] ∈ ('.', ')') )
```

![Screen Shot 2019-09-09 at 13 25 02](https://user-images.githubusercontent.com/10897531/64527102-5b34e080-d305-11e9-86e0-4b5263eae24c.png)

**Comment by pfitzseb** [comment] 2019-09-09 12:04
Yeah, this is by design and can't be configured, afaict. Moving to a tree-sitter grammar should fix the issue, but we're not quite ready for that yet ;)

**Closed by pfitzseb** 2019-09-09 12:04 UTC
Labels: bug
