### ISSUE TITLE
[BUG] Editor not responding for large for loop

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [JunoLab/Juno.jl#318] opened 2019-06-24 21:07 UTC
## Details
- Atom version: 1.38.2
- Julia version: 1.1.1
- OS: Ubuntu 19.04
- Package versions:
  - Atom.jl: 0.8.5
  - julia-client: 0.8.9
  - ink: 0.10.10

### Steps to reproduce

1. Run script below

```julia
using LightXML
using Printf

A=randn(25000,3)

xdoc = XMLDocument()

# create & attach a root node
xroot = create_root(xdoc, "Nodes")

for i=1:size(A,1)
    # Create string
    s="" # empty string
    for j=1:size(A,2)
        s*=@sprintf("%.8E, ",A[i,j])
    end

    # create the first child
    xs1 = new_child(xroot, "Node")
    set_attribute(xs1, "id", @sprintf("%i",i))
    # add the inner content
    add_text(xs1, s[1:end-2])

end
```
If I run the above I keep getting a "Editor not responding" error. Am I doing something wrong or is this a bug? 

![Screenshot from 2019-06-24 22-02-31](https://user-images.githubusercontent.com/8392709/60051895-eff74d00-96cb-11e9-8715-43aa1a0cfc2e.png)

**Comment by pfitzseb** [comment] 2019-06-25 07:43
I can't repro this issue, but I think the issue is that `xroot`'s and `xdoc`'s DOM representation are too big or something like that.

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-06-25 07:57
@pfitzseb thanks for checking this out. 

Have you tried using `A=randn(250000,3)` or an even larger array? 

Is "xdoc's DOM representation" a Julia thing or a LightXML thing? (I'm wondering if I should raise the issue with LightXML).

**Comment by pfitzseb** [comment] 2019-06-25 07:59
It's a Juno thing, so you are in the right place :) And yes, bigger arrays will probably crash the editor for me as well.
As a short term workaround you can just close the workspace and take care to never display `xroot`'s or `xdoc`'s content in the editor ever.

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-06-25 08:09
Thanks I tried it and it works. :tada:

**Comment by pfitzseb** [comment] 2019-08-07 13:36
Fixed with https://github.com/JunoLab/Atom.jl/commit/445e3c9819b77cbbd79f73d314fbbaf540ad2cc3, afaict.

**Closed by pfitzseb** 2019-08-07 13:36 UTC
Labels: bug
