### ISSUE TITLE
Julia Client - Internal Error (afterusing method in Atom)

### ISSUE THREAD

**Issue by TeeKay18** [JunoLab/Juno.jl#396] opened 2019-10-14 20:33 UTC
I'm having a bit of hard time while writing code in Julia language with Atom editor. When I'm trying to edit anything inside the code (while running Julia Client), this error shows up nearly every single time: 

![image](https://user-images.githubusercontent.com/20844643/66780623-95c80500-eed1-11e9-9856-5bc89cc2bbfa.png)

The good news is that I don't have any problems with writing the code in Julia and compiling it, everything else except that error message works the way it should, at least it seems so. 

While I was debugging in Juno, I was advised to send the info when reporting any issue, so I do down there: 

> # Atom:
Version: 1.40.1
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.11.2
Config:
{
  "firstBoot": false,
  "juliaPath": "C:\\Users\\xxxx\\AppData\\Local\\Julia-1.2.0\\bin\\julia.exe",
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}
# ink:
Version: 0.11.5
Config:
undefined
# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}
# language-julia:
Version: 0.19.1
Config:
undefined
# language-weave:not installed
# indent-detective:
Version: 0.4.0
Config:
undefined
# latex-completions:
Version: 0.3.6
Config:
undefined
# versioninfo():
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (i686-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  WORD_SIZE: 32
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, ivybridge)
Environment:
  JULIA_EDITOR = "C:\Users\xxxx\AppData\Local\atom\app-1.40.1\atom.exe"  -a
  JULIA_NUM_THREADS = 2
    Status `C:\Users\xxxx\.julia\environments\v1.2\Project.toml`
  [c52e3926] Atom v0.11.1
  [c87230d0] FFMPEG v0.2.3 #tmp (https://github.com/giordano/FFMPEG.jl)
  [28b8d3ca] GR v0.41.0
  [e5e0dc1b] Juno v0.7.2
  [91a5bcdd] Plots v0.27.0
  [27ebfcd6] Primes v0.4.0
  [b8865327] UnicodePlots v1.1.0

In case that's not enough details, I'm obviously open for anything else you need. Any ideas how should I solve this particular problem? Thank you in advance.

**Comment by pfitzseb** [comment] 2019-10-15 07:45
The root cause probably is that you have installed a 32bit Julia on a 64bit system.

This still shouldn't error like that though, imho.

**Comment by pfitzseb** [comment] 2019-10-15 08:04
Alright, the problem is fixed on our side by https://github.com/JunoLab/Atom.jl/commit/681115c028d6dcd4e8ffccf1f5a2db2721abcdc2.

I'd still recommend using a 64-bit Julia installation for now.

**Closed by pfitzseb** 2019-10-15 08:04 UTC
