### ISSUE TITLE
[BUG] Navigating away from Atom while evaluating, then back after it finishes crashes Atom

### ISSUE THREAD

**Issue by maccam912** [JunoLab/Juno.jl#338] opened 2019-07-30 14:42 UTC
Firstly: This happens to me on Julia 1.1 and 1.3 with both stable package versions and the latest dev versions. Atom used to work just fine for me so it might be something I did, but I've cleared out ~/.julia and reinstalled Atom and it happens on fresh installs.

## Details
- Atom version: 1.39.1
- Julia version: 1.3.0-alpha.0
- OS: Macos 10.14.5
- Package versions:
  - Atom.jl: 0.8.8 (recent master, bug happened with lastest stable too)
  - julia-client: 0.8.12-beta2
  - ink: 0.10.11

### Steps to reproduce

1. Start evaluating a a line of Julia, easier if it takes awhile to finish.
2. While it is evaluating navigate away from Atom so a different program has focus (I switch to Firefox)
3. After the notification that evaluation has finished, switch back to Atom and try to interact. Atom crashes and produces a crash report on Mac (attached)

I don't know enough about debugging Atom crashes to help more than that for now, but if you let me know what I can do to get more info I'll help as much as I can.

[crash.txt](https://github.com/JunoLab/Juno.jl/files/3447303/crash.txt)

**Comment by shipengcheng1230** [comment] 2019-07-30 16:35
I have the same issue. It's also reproducible when connecting to remote Julia session.

**Comment by ianfiske** [comment] 2019-07-30 20:32
I upgraded Atom to 1.39.1, and julia-client to 0.8.12-beta2 today and then started experiencing the same problem with an error stack very similar to the crash.txt posted above.

**Comment by JstaClarkey** [comment] 2019-07-31 22:19
Thanks to @ianfiske for the cross-post. My issue on Atom's Github was closed because it was in the wrong repo. We have recreated the issue on another mac machine by installing the latest Atom, Julia and Juno via Homebrew and by regular installation. Both machines were updated to Mojave (MacOS 10.14.6), but not fresh installed. The problem existed in Sierra too (MacOS 10.12.6)

**Comment by AshtonSBradley** [comment] 2019-07-31 22:46
could also be related to https://github.com/atom/atom/issues/19713

**Comment by AshtonSBradley** [comment] 2019-07-31 22:48
We now have this bug on 3 different imacs. 2013, 2015, 2019, all running Mojave. It was also evident on HighSierra for the 2015 machine prior to upgrade to Mojave.

**Comment by AshtonSBradley** [comment] 2019-07-31 23:10
It seems to have developed last week when the update sequence to Juno involving alpha, beta etc, went through

**Comment by pfitzseb** [comment] 2019-08-01 09:12
From my limited tests, deactivating the `Notifications` option in the julia-client settings (see below) circumvents the crash. Can you try that and report back?
![image](https://user-images.githubusercontent.com/6735977/62280956-2b183900-b44d-11e9-95f2-1593e29c9f63.png)

**Comment by ljschumacher** [comment] 2019-08-01 13:24
Disabling julia-client notifications seems to have fixed it for me

**Comment by logankilpatrick** [comment] 2019-08-01 14:25
Seems to be working for me as well!

**Comment by maccam912** [comment] 2019-08-01 20:44
And for me too!

**Comment by AshtonSBradley** [comment] 2019-08-01 22:13
works for me also

**Comment by pfitzseb** [comment] 2019-08-02 09:33
Upstream issue: https://github.com/electron/electron/issues/18701

Will be fixed with https://github.com/JunoLab/atom-julia-client/pull/581.

**Comment by maccam912** [comment] 2019-08-02 13:10
Excellent news pfitzseb! Would you like me to close this issue?

**Comment by pfitzseb** [comment] 2019-08-02 13:58
Will close this once the new release is out :)

**Closed** 2019-08-07 08:27 UTC
Labels: bug
