### ISSUE TITLE
REPL not working after script is sent to it

### ISSUE THREAD

**Issue by HenriDeh** [JunoLab/Juno.jl#231] opened 2019-01-25 17:01 UTC
I use juno on atom. I start julia using the normal procedure. The REPL pane is fully functionnal as long as I do not execute from a .jl file. 

The bug occurs when I execute a line from a file (opened in atom), using Ctrl + Enter, the execution is normal. What happens is that I cannot write commands in the REPL anymore. If I type next to "Julia>" nothing happens. If I use Ctrl + Enter to execute another block from the script, no problem, the output is printed in the REPL.

If I kill the julia process then restart it, the REPL is functionnal again, until I execute a block from a script again. This is inconvenient since it erases the workspace.

**Comment by pfitzseb** [comment] 2019-01-25 18:49
Duplicate of https://github.com/JunoLab/Juno.jl/issues/228 -- update your Atom.jl version and things should work fine again.

**Closed by pfitzseb** 2019-01-25 18:49 UTC
