### ISSUE TITLE
REPL prints incorrect return values

### ISSUE THREAD

**Issue by evanfields** [JunoLab/Juno.jl#119] opened 2018-03-13 14:02 UTC
I've noticed that sometimes the in-Juno REPL will print the wrong return value for a function, even though the value of `ans` showed in the workspace pane is correct. How to reproduce:

In Juno, kill Julia and start a fresh session. I've noticed this a few times in the middle of a long session, but I can't reliably reproduce without a fresh session.
```
Julia has exited. Press Enter to start a new session.
Starting Julia...
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> x = rand(1000); mean(x)
0.7416772887268637

julia> mean(x)
0.5017561285443812
```
(Keep calling `mean(x)` at this point and keep seeing `.502...`, which appears to be the correct value.)

After the first `mean(x)` call, `ans` will show `.502...`, and if I instead bind a variable `u1 = mean(x)` then `u1` will have the correct value, but an incorrect value will still be printed.

This behavior does not occur if I open a fresh regular non-Juno REPL and try the same.

My system: 
`julia-client` 0.6.10, `language-julia` 0.15.0, `ink` 0.8.3,
```
julia> Pkg.status("Atom")
 - Atom                          0.6.11             master

julia> Pkg.status("Juno")
 - Juno                          0.4.0              master

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17* (2017-12-13 18:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 1600X Six-Core Processor
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Barcelona)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, generic)
```

**Comment by pfitzseb** [comment] 2018-03-15 11:04
Ok, I could finally reproduce this -- crucial point is that the Workspace must be open. Turns out that the first time you eval `x = rand(100000); mean(x)` the last element of `x` will be printed in the REPL.
Super weird, but I should be able to figure out why this happens now.

**Comment by pfitzseb** [comment] 2018-03-15 12:30
Alright, this should hopefully be fixed now, but I don't really understand why that bug happened and why my fix fixes it. Oh well...

**Closed** 2018-03-15 12:29 UTC
Labels: bug

**Comment by ssfrr** [comment] 2018-05-30 21:40
I also haven't been able to get a reproducible case here, but it's happened to me before and I don't use the Workspace, so I'm not sure that's the root cause.

Here's where I reported it before:
https://github.com/JuliaMath/FixedPointNumbers.jl/issues/103

**Comment by pfitzseb** [comment] 2018-05-31 09:06
Unless you've seen that error recently, chances are that it has the same cause and is fixed now. Feel free to reopen this if not though.
