### ISSUE TITLE
Juno freezes intermittently when running code from script

### ISSUE THREAD

**Issue by fisherc2** [JunoLab/Juno.jl#103] opened 2018-01-31 17:43 UTC
Overall, the updates to Juno have made it faster and more responsive, but I have encountered cases where it freezes when code is ran from the editor (by highlighting and pressing ctrl + Enter or clicking the run button). The problem is intermittent. Sometimes it works for hours. Other times it consistently freezes for multiple, consecutive attempts. Usually, all of the code executes as verified with a print statement. However, the gear icon does not disappear and the REPL becomes unresponsive. This has happens on two machines: Ubuntu 16.04 and Mac 10.11.6. I am using Julia .6.2, Atom 1.23.3 and the current version of Juno. 

I want to report this in case there are other people experiencing this problem, but have not reported the issue since there is no error message to report.

**Comment by pfitzseb** [comment] 2018-02-01 10:24
Thanks for the report. I suspect this is caused by the julia process dying sometime during execution, but can't be sure without additional info.

The next time this happens, can you open the Electron dev tools via `Ctrl-Shift-I` (or `Cmd-Shift-I`) and check the console there for errors?

**Comment by fisherc2** [comment] 2018-02-01 10:55
Thanks for your reply. Strangely, I do not get an error in the console when this happens.  I do get an error when I click the stop button:

```
Error: Something went wrong while evaluating.
(anonymous) @ evaluation.coffee [sm]:44
_tickCallback @ internal/process/next_tick.js:103
```

I also have a warning when I start Atom.
```
IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:121025
```
Hopefully, one of these messages is informative.

**Comment by fisherc2** [comment] 2018-02-01 11:02
Also, I only receive the first error when cancelling a frozen process. If I start and stop Julia, I do not receive the error. So I suspect it might be useful.

**Comment by pfitzseb** [comment] 2018-02-01 11:13
I'm afraid it isn't particularly useful; you'll also get that message when trying e.g. `sleep(3)` and clicking the stop button.

Can you share some code that exhibits those issues?

**Comment by fisherc2** [comment] 2018-02-01 11:38
Bummer. Well, the following is sufficient to produce the error on my machines:

```
addprocs(4)
@everywhere using DistributedArrays
x = [rand(100,100) for i in 1:1000]
d = distribute(x)
println("Finished")
```

This also produces the error:

```
addprocs(4)
println("Finished")

```
The following seems to work, however: 

```
using Plots
plotlyjs()
plot(randn(10),randn(10))
println("finished")
```
So perhaps `addprocs()` is related to the error.

**Comment by pfitzseb** [comment] 2018-02-01 11:52
Indeed, `addprocs()` fails/doesn't terminate for me when executed in an editor, as opposed to what happens in the REPL.

**Comment by pfitzseb** [comment] 2018-02-01 13:39
MWE: `Atom.didWriteToREPL(() -> addprocs(3))`.

**Comment by SimonDanisch** [comment] 2018-02-02 10:58
Looks similar to my problem, but I'm pretty sure I don't use `addprocs` anywhere in my code.

**Comment by pfitzseb** [comment] 2018-02-02 11:07
Are you doing any fancy stuff with `STDOUT` or `STDERR`?

**Comment by SimonDanisch** [comment] 2018-02-02 11:10
For all I know, I don't... Although the problematic code might have used pipes + run(`...`), if I think about it...

**Comment by pfitzseb** [comment] 2018-02-02 12:23
The `addprocs` issue is fixed with https://github.com/JunoLab/Atom.jl/commit/da370f97461a1878ae5bb7f8c6725f69debd1d30, and I'd wager the same is true for what @SimonDanisch saw.

**Closed by pfitzseb** 2018-02-02 12:23 UTC
Labels: bug
