### ISSUE TITLE
Cannot open remote Julia REPL console

### ISSUE THREAD

**Issue by staticfloat** [JunoLab/Juno.jl#226] opened 2019-01-18 20:02 UTC
## Details
- Atom version: 1.34.0
- Julia version: 1.0.3
- OS: macOS (local) Linux (remote)
- Package versions:
  - Atom.jl: 0.7.12
  - julia-client: 0.7.13
  - ink: 0.9.14

### Steps to reproduce

When I open Atom, connect to a remote server, then run the `Start Remote Julia Process` menu item, I get the following error:

<img width="461" alt="screen shot 2019-01-18 at 11 56 08 am" src="https://user-images.githubusercontent.com/130920/51410270-f0862900-1b18-11e9-90bc-4e494af8168e.png">

The link to an existing issue takes me to one that is only tangentially related.

**Comment by pfitzseb** [comment] 2019-01-18 21:13
Did you have the tmux option enabled? If so then the problem is that the REPL pane wasn't opened in your session yet (which means the terminal isn't initialised yet) but tmux sends an escape code to switch to the alternate buffer which isn't properly handled by our terminal library if it isn't attached to the DOM yet.

I guess I'll force the REPL pane to open when booting which should hopefully fix the issue.

**Comment by staticfloat** [comment] 2019-01-18 22:06
I do have the `tmux` option enabled, that's true.

**Comment by pfitzseb** [comment] 2019-01-21 10:17
Upstream fix: https://github.com/xtermjs/xterm.js/pull/1905

**Comment by pfitzseb** [comment] 2019-02-03 14:54
Actual upstream fix: https://github.com/xtermjs/xterm.js/pull/1927

**Comment by pfitzseb** [comment] 2019-03-18 08:12
Upstream fix is in, so this actually works now :)

**Closed by pfitzseb** 2019-03-18 08:12 UTC
Labels: upstream
